### ISSUE TITLE
Update sample project

### ISSUE THREAD

**Issue by adamsuskin** [schneiderandre/ASCFlatUIColor#2]
Upon forking and cloning the repo, the project is obviously not up-to-date for the latest iOS version. However, after XCode performs its "project upgrades," the project still cannot build because of a linker error:

```
ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Perhaps the necessary Pods subproject / workspace can be included in the repo?

**Comment by adamsuskin** [comment]
Whoops. Premature issue. Just need to run `pod install` (still quite new to Cocoapods). Sorry!

**Comment by schneiderandre** [comment]
No worries! Thanks anyway :smile:
